### ISSUE TITLE
TypeError: verifyPassURIOffline is not a function

### ISSUE THREAD

**Issue by zinwalin** [kety-folf/Covid-Cert-Scanner#1]
![image](https://user-images.githubusercontent.com/5416196/145760081-c690277f-737a-49aa-b9e3-5b02b850f15a.png)

**Comment by kety-folf** [comment]
ok well this is the package that is causing that issue 
https://www.npmjs.com/package/@vaxxnz/nzcp 
and it says that is in there so i will do some looking into it as to why that error happens

**Comment by kety-folf** [comment]
I will say double check everything is imported correctly  and if it is all there i will have a look and see why its not

**Comment by kety-folf** [comment]
if you pull the new server code it should now work
